### ISSUE TITLE
Are the end/endWith functions needed? What is purpose of these functions?

### ISSUE THREAD

**Issue by ashleydavis** [structured-log/structured-log#15]
I'm looking to simplify the core a little bit so that it is easier to restructure for batching.

I'm considering removing the log.end and Pipeline.end (and related) functions.

They appear to only be used in file-sink.tests.js and look like they might be replaced by the *flush* function.

Are my assumptions correct?

Can these functions be stripped out and later replaced with *flush*? (when batching is online).

**Comment by nblumhardt** [comment]
Hi Ashley - `end()` is more akin to `dispose()` than `flush()`, for example allowing files to be closed when a logger is no longer needed. I don't think `flush()` will extend to these cases, but could be wrong :-) Cheers!

**Comment by ashleydavis** [comment]
Would it be better to have a dispose function on each sink?

**Comment by nblumhardt** [comment]
I think that's already the case - `endWith()` is the sink's dispose method, essentially. I think it'd be error-prone to have users do this manually per-sink, not sure if that's what you mean?

**Comment by ashleydavis** [comment]
I still don't really understand the purpose of this. Do users have to call `end` explicitly when they are done with a log? I must be misunderstanding this because it doesn't seem like a great API.

Can you give me an example of why a user would need to call `end()`?

The only example I can see in the code is in *file-sink-tests.js* and that to me seems like it would be better served by a flush function?!

**Comment by nblumhardt** [comment]
Hi Ashley, I guess there are two intertwined scenarios:

- Closing the log _before_ an app shuts down, and
- Closing the log _at_ shutdown

I think the latter is probably the same as `flush()`, since the termination of the process will release file handles anyway.

The former seems like it's hard to do with `flush()` - though it is probably the less common scenario. Flush for a synchronously-written file might not do anything, while `end()` would close the file.

We could probably axe `end()`, but _"how do I close a log file?"_ will definitely come up as a question at some point. If we make a big win on complexity by dropping it I think that would be a fair call - if the overhead is low however it is probably worth keeping.

Is `end()` throwing a spanner in the works for batching?

Cheers!

**Comment by nblumhardt** [comment]
(Renaming `end()` to `close()` seems like a reasonable thing for us to consider, too :))

**Comment by ashleydavis** [comment]
Thanks Nick, just calling it close really clears things up ;)

It's not necessarily a problem for batching, although if it could be moved out of the *pipeline* it might make it easier to figure out how to properly integrate batching.

So I'd definitely like to rename it to `close`, if that's ok? That cleared things up for me straight away (as to its purpose at least).

Is the purpose of this then just to call the `end` function on sinks that are attached to the log?

**Comment by nblumhardt** [comment]
:+1: sounds like a plan :-)

Yes, I think in the current pipeline it's just a matter of calling the end (`endWith()`?) functions; renaming these `close` mightn't be a bad idea either - definitely an option.

Once `flush()` is in there I'd expect `close()` to possibly flush as well as close the sinks, but probably needs a few things to fall out first.

Regarding fitting things into the pipeline, shall we open a ticket to brainstorm some approaches? It's a pretty fiendishly hard design problem... But those are the best kind ;-)

**Comment by ashleydavis** [comment]
I've already changed `end` to `close` and a bunch of small refactor/renames to make the pipeline code more understandable for me. 

Check #19 for the commits. 

I'm still working on integrating batching with the new `close` function, but that should be in tomorrow hopefully.
