### ISSUE TITLE
What is the meaning of destructure parameter of the enrich function?

### ISSUE THREAD

**Issue by ashleydavis** [structured-log/structured-log#18]
A boolean *destructure* parameter is passed into the *enrich* function and I'm wondering what the meaning of it is. 

If *destructure* is enabled it means that object properties get captured to the event properties as objects... otherwise *toString()* is called and the object is converted to a string before being captured to the event properties.

What is the intent behind this?

**Comment by IanYates** [comment]
Seq and other Serilog sinks like Elasticsearch accept the destructured output and allow for fancy searching.  For example, I could log a "patient" object in a few of my messages, and that patient object has an Id.  I can go to Seq and do something like Patient.Id == '222' and get all the logs relating to that patient.  It also means I don't have to have a .ToString() on my patient object since I can just rely on the various properties being available in the log for me.

Structured-log probably needs some smart defaults when trying to handle some objects though, like dates and the like, since destructuring a date property of a given object is probably silly since its .ToString() or an ISO format would make more sense.

**Comment by ashleydavis** [comment]
That's cool and I get what you are saying. Except for one thing... I'm probably just missing the point but why use the '@' symbol at all? Why not make that the default behaviour?

I'm still wondering what is the use of the *destructure* parameter is in terms of the *enrich* function. That seems to me to be a different situation than what you have explained.

Thanks for trying to fill the holes in my knowledge ;)

**Comment by IanYates** [comment]
The destructure flag is set when there's an @ symbol at the start of the name.

Why not make it the default?  Good question :)  I guess because often the .ToString() is enough and is expected to be fast/cheap to call and ought to not fail.  Delving into all of the properties, and their properties, and so on, could be expensive so it's something that you opt-in to with an "@" symbol.  

Of course, the default being the way it is could also be a holdover from C#/.NET land.  @nblumhardt would have a lot more knowledge here than me.  I'm just an interested observer who's keen to jump in and help when I have time & you've got things where you want them.  For example, when the API surface is decided I'd like to get some TypeScript definitions sorted out, etc.

**Comment by nblumhardt** [comment]
> expected to be fast/cheap to call and ought to not fail

Yup, that's the crux of it - serializing arbitrary things is a bit risky. Circular dependencies in particular make for some challenges. The `@` is kinda like saying: "trust me, I want to serialize this!" :-)

Many types also render a bit better with `toString()` than they do when viewed as a bag of properties. Here's `URL`:

![image](https://cloud.githubusercontent.com/assets/342712/8980765/7b003324-36f6-11e5-9b5e-7229bc3e3c43.png)

Finally, depending on the design, there's an additional cost to `@` that is best avoided when possible. If the event is logged immediately, all is good here:

```js
var x = {a: 10};
log("Hey, here is {@x}!", x)
// -> "Hey, here is {a: 10}!
x.a = 11;
```

However, once batching is part of the picture:

```js
var x = {a: 10};
log("Hey, here is {@x}!", x)
x.a = 11;

// Some time later..
// -> "Hey, here is {a: 11}!
```

To prevent this, parameters that come in via `@` destructured properties are cloned (in Serilog; we haven't got this implemented in _structured-log_ so far IIRC). Not destructuring by default means avoiding the cost of cloning values when we don't need to.

HTH!
