### ISSUE TITLE
Unable to check out fork due to submodule issue

### ISSUE THREAD

**Issue by nblumhardt** [structured-log/structured-log#3]
Not sure what might cause it, will investigate when I have a chance but posting in case it is something obvious.

Attempting to check out a clean fork (`nblumhardt/structured-log`) yields:

```
"C:\Program Files (x86)\Git\bin\git.exe" clone -v --recurse-submodules --progress "https://github.com/nblumhardt/structured-log.git" "C:/Development/Open Source/nblumhardt/structured-log"
Cloning into 'C:/Development/Open Source/nblumhardt/structured-log'...
POST git-upload-pack (250 bytes)
remote: Total 327 (delta 73), reused 0 (delta 0), pack-reused 172
Checking connectivity... done.
Submodule 'dist/bower' (https://github.com/codecapers/serilogjs-bower) registered for path 'dist/bower'
Cloning into 'dist/bower'...
fatal: reference is not a tree: 2abea1ddf585e2fc4093dbe1bf6fa699c60b8ab5
Unable to checkout '2abea1ddf585e2fc4093dbe1bf6fa699c60b8ab5' in submodule path 'dist/bower'
Done
```

**Comment by ashleydavis** [comment]
The sub-module is the repo for the bower package. When you run 'gulp build-bower' it builds a client-side version for deployment to bower. When this sub-repo is committed and pushed the bower package is update.

This is probably broken because today I transferred serilogjs-bower from codecapers to the structured-log organisation and renamed it to structured-log-bower. 

I had assumed github would take care of this but there must be something I need to change to redirect to the transferred repo. 

Will look into it ASAP.

**Comment by ashleydavis** [comment]
This should be fixed now. I couldn't clone it either (although my existing clone) continued to work ok. As I expected the path to the sub-module bower repo had to be updated after the repo was transferred to the structured-log organisation and renamed to structured-log.

Please try to clone again and close this issue if it works for you.

**Comment by ashleydavis** [comment]
Something is still going wrong... I'm continuing to look into this.

**Comment by ashleydavis** [comment]
Ok it does seem to work now. For some reason I had to update and commit the sub-module. Please try and clone it again.

**Comment by nblumhardt** [comment]
Will do ASAP, thanks Ashley!

**Comment by nblumhardt** [comment]
Works now, cheers!
