### ISSUE TITLE
Issues including sinks in the npm package

### ISSUE THREAD

**Issue by ashleydavis** [structured-log/structured-log#4]
Consider the existing NodeJS example I put together recently:

```
var serilog = require('structured-log');
var consoleSink = require('structured-log/serilog-console-sink');

var log = serilog.configuration()
    .writeTo(consoleSink())
    .createLogger();

log.information('Hello this is some information.');

log.warning('This is a warning.');

log.error('This is an error.');
```

Granted this needs to change, and should at least look like this: 

```
var structuredLog = require('structured-log');
var consoleSink = require('structured-log/console-sink');

var log = structuredLog.configuration()
    .writeTo(consoleSink())
    .createLogger();
```

The method of including the extra file from the module in the following way kind of irks me:

```
var consoleSink = require('structured-log/console-sink'); 
```

But this seems to be the way it is done when you include multiple modules in a NodeJS package (or maybe someone can correct me?)

I'd much prefer it to look like this

```
var consoleSink = require('structured-log-console-sink'); 
```

But that would require a separate package for the sink.

The other option would be to just include all built-in sinks under the main object, eg:

```
var log = structuredLog.configuration()
    .writeTo(structuredLog.sinks.console())
    .createLogger();
```

We had talked about not doing this... but this is actually the way it has to be done on client-side/browser. So it would make the server-side and client-side examples more similar.

But then there would still be a discrepency in NodeJS, where 3rd party sinks are loaded using require(...) as they should be:

```
var structuredLog = require('structured-log');
var mySink = require('some-3rd-party-sink');

var log = structuredLog.configuration()
    .writeTo(mySink())
    .createLogger();
```

Thoughts on this?

**Comment by nblumhardt** [comment]
On the server side, the majority of projects I've seen split things into fine-grained packages, so:

```js
var structuredLog = require('structured-log');
var consoleSink = require('structured-log-console-sink'); 
```

Given npm is so easy to use, the overhead of doing multiple installs is pretty low:

```
npm install structured-log --save-dev
npm install structured-log-console-sink --save-dev
```

Over the long term, going this way puts the included sinks on an equal footing with community-provided ones, which is good for several reasons:

1. Strong community is encouraged
2. Public APIs are well-defined and validated since they're used by all sinks
3. It makes "better" versions of included things able to compete, e.g. `structured-log-super-console-sink`

I'm totally fine with the way things are now, but I see a lot of advantages in the fully-separated model as well, if you are considering a change here. Tough call to make - if I started Serilog again today afresh I'd use the separated model, but early on the one-package model did work well.

**Comment by ashleydavis** [comment]
I have mixed feelings about this.

From a theoretical view point I would like fine-grained separately-installed packages.

From a practical view point I think it's a pain and the most common sinks should be included.

After thinking about it... I think we should separate them right now. We can always find a way to bring them back together should we later deem that to be the right way to do things. It's going to be very difficult to split up the sinks once people start using this.

**Comment by nblumhardt** [comment]
:+1:, sounds like a good option.

**Comment by aggieben** [comment]
How would one currently load an included sink on the frontend?  I'm using npm to grab packages, but there's no `structured-log-console-sink` package, and the `structured-log` package doesn't do anything to make `console-sink.js` visible to my loaders (that I'm aware of).

**Comment by ashleydavis** [comment]
Unfortunately the readme isn't quite up to date yet.

However there are some included examples that do work.

This is the setup code from the nodejs example:

var structuredLog = require('structured-log-dev');
var consoleSink = require('structured-log-dev/console-sink');

var log = structuredLog.configure()
.writeTo(consoleSink())
.create();
log.info('Hello this is some information.');

You can find the full example here:
https://github.com/structured-log/structured-log/tree/dev/examples/nodejs

**Comment by ProTip** [comment]
Hola,

First I'd like to say this is pretty awesome.  Just started using nodejs(coffee script) for a major project 3 months ago.  Looking to push structured logging at my current company and after using Serilog in the past(I miss C# too :| ) and absolutely loving it this came up on my radar pretty quick when looking into logging for JS.  Unfortunately my project is largely a CLI and Bunyan unfortunately requires some crazy piping shinanigans to get human readable log messages with a 3 year issue open for alternatives..  And I mean, Serilog in js(!) and every language/platform should have a Serilog.

On point, I had some trouble with the README due to the recent changes.  I would be happy to do up a pull request with working changes as I run across them if you'd be interested.

**Comment by ashleydavis** [comment]
Please do contribute! 

The code usage is meant to match the readme, the readme itself was spec'd so that we'd have something  to aim for with the code. If the code doesn't match the readme please update the code. If the readme seems wrong pls update the readme. 

I'm currently going through a process of getting our production servers converted to structured log. I'm finding  a few issues myself in the process  which I'll look into in due time.

**Comment by Wedvich** [comment]
Closing this as it no longer reflects the current situation. The `ConsoleSink` is common enough to be included by default, but the other sinks (such as the HTTP sink or Seq sink) are good to keep as separate NPM packages like they currently are.
