### ISSUE TITLE
Remove extraneous dev branch

### ISSUE THREAD

**Issue by Wedvich** [structured-log/structured-log#41]
There are currently two branches: `dev` and `master`. Development is being done on `dev`, obviously, and when it's time for a release, it's merged into `master`. However, I'd argue that this split doesn't provide any value. When anything in `dev` will eventually end up in `master` anyway, it's a redundant extra step. And since we're using tags to mark the release versions, there's no need for merge commits to mark them too, nor keeping an extra branch for maintenance.

Having just a single mainline branch would simplify housekeeping and the handling of PRs, since any actual changes are performed in forks anyway. @nblumhardt @ashleydavis thoughts?

**Comment by nblumhardt** [comment]
The dev branch has proven useful in the Serilog projects, but probably due to the pre-release publishing option provided by NuGet. When we receive PRs, they can go into dev and then be more widely tested by people pulling the latest pre-release packages (and thus changes can cascade out into the -pre versions of dependent packages).

Definitely not crucial though - if it'd be easier just to release from master by tagging, fine by me :-)
